# Generated by Django 4.2.6 on 2023-10-23 23:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('PORTIFOLIO', 'Portfolio'), ('PROJETOS', 'Projects'), ('CLT', 'CLT'), ('COMUNIDADE', 'Community')], max_length=100)),
                ('description', models.TextField()),
                ('path', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('published', models.BooleanField(default=False)),
                ('like', models.IntegerField(default=0)),
                ('date_photography', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
