# Generated by Django 4.2.6 on 2023-10-24 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecatalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=200)),
            ],
        ),
    ]
