# Generated by Django 4.2.6 on 2023-10-25 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitecatalogo', '0002_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='senha',
            new_name='password',
        ),
    ]
